# Generated by Django 4.0.2 on 2022-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_instructions',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
