# Generated by Django 4.0.2 on 2022-04-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_reference',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
