# Generated by Django 4.0.2 on 2022-04-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_recipe_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
