# Generated by Django 4.0.2 on 2022-04-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_recipe_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeinstruction',
            name='instruction_text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='RecipeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_text', models.CharField(default='', max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
