# Generated by Django 4.0.2 on 2022-04-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipeinstruction_instruction_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='num_instructions',
        ),
    ]
