# Generated by Django 4.0.2 on 2022-04-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_recipeingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='equipment_quantity',
            new_name='ingredient_quantity',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='equipment_text',
            new_name='ingredient_text',
        ),
    ]
