# Generated by Django 4.0.2 on 2022-04-08 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0017_rename_equipment_quantity_recipeingredient_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='own_recipes',
            field=models.ManyToManyField(blank=True, related_name='own_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
