# Generated by Django 4.0.2 on 2022-04-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_recipe_own_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='own_recipes',
        ),
    ]
