# Generated by Django 4.0.2 on 2022-04-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
