# Generated by Django 4.0.2 on 2022-04-17 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0024_rename_user_recipe_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='auth_user',
        ),
        migrations.AddField(
            model_name='recipe',
            name='submitted',
            field=models.ManyToManyField(blank=True, related_name='submitted', to=settings.AUTH_USER_MODEL),
        ),
    ]
