# Generated by Django 4.0.2 on 2022-04-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_remove_recipe_auth_user_recipe_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='submitted',
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
