# Generated by Django 4.0.2 on 2022-04-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_remove_recipe_submitted_recipe_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
