# Generated by Django 4.0.2 on 2022-04-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_remove_recipe_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
