# Generated by Django 4.0.2 on 2022-04-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_recipe_recipe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_diet',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
