# Generated by Django 4.0.2 on 2022-04-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_recipe_recipe_diet_recipe_recipe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_diet',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_type',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_time',
            field=models.CharField(choices=[('5-15', '5 to 15 minutes'), ('15-30', '15 to 30 minutes'), ('30-60', '30 minutes to an hour'), ('60+', 'Over an hour')], default='5-15', max_length=30),
        ),
    ]
