# Generated by Django 4.0.2 on 2022-04-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_remove_recipe_recipe_diet_remove_recipe_recipe_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('snack', 'Snack'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], default='breakfast', max_length=10),
        ),
    ]
