# Generated by Django 4.0.2 on 2022-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_remove_recipe_recipe_time_remove_recipe_recipe_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.CharField(choices=[('5-15', '5 to 15 minutes'), ('15-30', '15 to 30 minutes'), ('30-60', '30 minutes to an hour'), ('60+', 'Over an hour')], default='5-15', max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('snack', 'Snack'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], default='breakfast', max_length=10),
        ),
    ]
