# Generated by Django 4.0.2 on 2022-04-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_recipe_recipe_diet_alter_recipe_recipe_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_diet',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_type',
        ),
    ]
