# Generated by Django 4.0.2 on 2022-04-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_remove_recipe_recipe_diet_remove_recipe_recipe_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_diet',
            field=models.CharField(blank=True, choices=[('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('gluten-free', 'Gluten-Free'), ('nut-free', 'Nut-Free')], max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_time',
            field=models.CharField(choices=[('5-15', '5 to 15 minutes'), ('15-30', '15 to 30 minutes'), ('30-60', '30 minutes to an hour'), ('60+', 'Over an hour')], default='5-15', max_length=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('snack', 'Snack'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], max_length=10),
        ),
    ]
